---
#export VAULT_TOKEN=hvs.xxx
#export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
- name: test vault
  gather_facts: false
  hosts: all
  tasks:
    - name: get APP_TOKEN from vault
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'apps/data/my-app:APP_TOKEN') }}"
